apiVersion: v2
name: k0rdent-istio
description: Istio Helm chart that deploys Istio with multicluster multinetwork setup
version: "0.2.0"
appVersion: "0.2.0"
dependencies:
  - name: cert-manager-istio-csr
    version: "0.14.0"
    repository: "https://charts.jetstack.io"
  - alias: istiobase
    name: base
    version: "1.25.3"
    repository: "https://istio-release.storage.googleapis.com/charts"
  - name: istiod
    version: "1.25.3"
    repository: "https://istio-release.storage.googleapis.com/charts"
  - name: kgst
    condition: cert-manager-service-template.enabled
    alias: cert-manager-service-template
    version: "1.2.0"
    repository: oci://ghcr.io/k0rdent/catalog/charts