{{- if .Values.isManagement }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{ index .Values "k0rdent-istio" "repo" "name" }}
  namespace: {{ .Values.kcm.namespace }}
  labels:
    k0rdent.mirantis.com/managed: "true"
spec:
  {{- (index .Values "k0rdent-istio").repo.spec | toYaml | nindent 2 }}
{{- end }}